WIFI_SSID="yourWIFI"
WIFI_PASSWORD="YourPassword"
NTP_HOST="0.adafruit.pool.ntp.org"
TZ_OFFSET=-5
NTP_INTERVAL=60

# weather settings # imperial or metric
UNITS="imperial"

# openweathermap.org Data Authorization
OWM_API_TOKEN="Your Token"
OWM_ZIP="zip/post code"
OWM_COUNTRY="US" # Please use ISO 3166 country codes
OWM_USE_HTTPS=1