name: Release CI

on:
  release:
    types: [published]
    
jobs:
  upload-mpy-zips:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the current repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name:
      run: echo "${{ github.event.release.tag_name }}" > src/.version
    - name: Run MPY Action
      uses: adafruit/build-mpy@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        circuitpy-tag: "8.0.3"
        mpy-directory: "src"
        mpy-manifest-file: "mpy-manifest.txt"
        mpy-manifest-type: "exclude"
        zip-directory: "src"
        zip-filename: "weather-matrix-${{ github.event.release.tag_name }}.zip"