name: Release CI

on:
  release:
    types: [published]
    
jobs:
  upload-mpy-zips:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the current repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Create .version file
      run:
        echo '{ "version":"${{ github.event.release.tag_name }}" }' > src/.version
    
    - name: Run MPY Action
      #uses: adafruit/build-mpy@v2
      uses: jake1164/build-mpy@static-mpy-cross      
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        circuitpy-version: 10.0.3        
        mpy-directory: "src"
        mpy-manifest-file: "mpy-manifest.txt"
        mpy-manifest-type: "exclude"
        zip-directory: "src"
        zip-filename: "weather-matrix-${{ github.event.release.tag_name }}.zip"
